DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;

USE g1mkzvyu87y8a89l;

CREATE TABLE burgers (
	ID INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(255) NOT NULL,
	devoured BOOLEAN DEFAULT false,
    PRIMARY KEY (ID)
);

